spring:
  redis:
    port: 6379
    host: localhost
    timeout: 4
  datasource:
    username: root
    password: root
    url: jdbc:mysql://localhost:3306/test
    driver-class-name: com.mysql.cj.jdbc.Driver

  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update

jwt:
  secretKey: 38583a5affa17b1ff4b0dc664f55ec125282913f95f42aa4ad11de2198019ddf5c8bfc1bcee5b047cfa356fc61d2d679d278d0943479451518bf6325d58e2094
  auth:
    atk: ATK
    rtk: RTK

CLOVA:
  test:
    response: "{\"document\":{\"sentiment\":\"negative\",\"confidence\":{\"neutral\":0.14525136640572725,\"positive\":0.00186876227013191,\"negative\":0.8528798713241407}},\"sentences\":[{\"content\":\"싸늘하다.\",\"offset\":0,\"length\":5,\"sentiment\":\"negative\",\"confidence\":{\"negative\":0.9961358904838562,\"positive\":0.0036366574931889772,\"neutral\":0.0002274021098855883},\"highlights\":[{\"offset\":0,\"length\":4}]},{\"content\":\" 가슴에 비수가 날아와 꽂힌다.\",\"offset\":5,\"length\":17,\"sentiment\":\"negative\",\"confidence\":{\"negative\":0.927976131439209,\"positive\":0.07131962478160858,\"neutral\":0.0007042606011964381},\"highlights\":[{\"offset\":1,\"length\":15}]}]}}"
    error: "{\"status\":400,\"error\":{\"errorCode\":\"E001\",\"message\":\"Unsupported empty or blank text\"}}"