name: ci-cd
on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2



      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Build Docker img
        run: |
          docker build -t wlals4253/moy:${{github.sha}} .
          docker tag wlals4253/moy:${{github.sha}} wlals4253/moy:latest

      - name: Log in to Docker registry
        uses: docker/login-action@v1
        with:
          registry: docker.io
          username: ${{ secrets.DOCKER_USERNAME }}
          passowrd: ${{ secrets.DOCKER_PASSWORD }}

      - name: PUSH DOCKER
        run: |
          docker push wlals4253/moy:${{github.sha}}
          docker push wlals4253/moy:latest
